apiVersion: apps/v1
kind: Deployment
metadata:
  name: pit
  namespace: celso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pit
  template:
    metadata:
      labels:
        app: pit
    spec:
      containers:
        - name: pit
          image: celsonery/pit:v1.0.4
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pit-service
  namespace: celso
spec:
  selector:
    app: pit
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
