# build stage
FROM node:22.11.0-alpine3.20 as build-stage
RUN apk update && apk upgrade --no-cache
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --mode=production

# production stage
FROM nginx:stable-alpine as production
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
